simpligility/android-maven-plugin

src/main/java/com/jayway/maven/plugins/android/phase04processclasses/ProguardMojo.java
src/main/java/com/jayway/maven/plugins/android/phase09package/AarMojo.java

This commit alows obfuscated classes to be used while
building an AAR when proguard is enabled.
No dependencies are processed or included in the
classes.jar archive as that would cause potential code
duplication and affect dependency resolution.
The final application should take care of obfuscating
all depdendencies when applicable.
Signed-off-by: David Marques <dpsmarques@gmail.com>

Adding proguard support to library (AAR) projects

---

src/main/java/com/jayway/maven/plugins/android/phase_prebuild/ClasspathModifierLifecycleParticipant.java

This fixes the issues #530 is trying to fix but without breaking the provided jar workaround for IDEs

Fixing #529

---

src/main/java/com/jayway/maven/plugins/android/configuration/ManifestMerger.java
src/main/java/com/jayway/maven/plugins/android/configuration/VersionGenerator.java
src/main/java/com/jayway/maven/plugins/android/standalonemojos/ManifestMergerMojo.java
src/main/java/com/jayway/maven/plugins/android/standalonemojos/ManifestUpdateMojo.java
src/test/java/com/jayway/maven/plugins/android/configuration/VersionGeneratorTest.java

The current version generator acts wrongly if the version "1.0" is
followed by "1.0.1", "2.0".
Added a configurable version generator where the number of elements and
the number of digits per element are configurable through a version
spec. The spec is a comma-separated list of digits, one for each version
element.

Improvement of versionCode generator

---

src/main/java/com/jayway/maven/plugins/android/AbstractAndroidMojo.java
src/main/java/com/jayway/maven/plugins/android/phase_prebuild/ClasspathModifierLifecycleParticipant.java

https://github.com/simpligility/android-maven-plugin/issues/583#issuecomment-74657334
Close https://github.com/simpligility/android-maven-plugin/issues/585

Default includeLibsJarsFromAar to true

---

src/main/java/com/jayway/maven/plugins/android/phase09package/AarMojo.java

This should fix the problem described in #477

Prevent native libraries from transitive dependencies being added to aar

---

src/main/java/com/jayway/maven/plugins/android/standalonemojos/RunMojo.java

For your consideration: I'd like to simplify debugging of Android applications when using the android-maven-plugin. I am attaching initial sketch that does the job for me. I am ready to polish it according to your suggestions.
Annoying thing on debugging (at least for me) is to find a PID number of just launched process and establish JDWP forwarding, so I can connect my debugger to it. I believe all of this can be automated.
My pull request allows one to specify port number via -Dandroid.run.debug=1234 and the plugin then takes care about the rest.

Automatically forward JDWP connection

---

pom.xml

I believe this change was missed for this commit:
https://github.com/simpligility/android-maven-plugin/commit/c139368dc3643e20c31f78fb1ed42bc80fb31611

Change maven prerequisite to 3.0.4 to match the maven api version

---

src/main/java/com/jayway/maven/plugins/android/phase09package/ApkMojo.java

The META-INF includes functionality added back in stripped resources from the META-INF folder but only from 3rd party jar dependencies.  Not resources from the actual application.  So I added the output jar to the list of jars that are processed by the addMetaInf function to include application resources as well.

Add meta includes from main jar artifact

---

src/main/java/com/jayway/maven/plugins/android/AbstractAndroidMojo.java
src/main/java/com/jayway/maven/plugins/android/AbstractPublisherMojo.java
src/main/java/com/jayway/maven/plugins/android/standalonemojos/PublishApkMojo.java
src/main/java/com/jayway/maven/plugins/android/standalonemojos/PublishListingMojo.java

Implements #601. I followed [this](http://docs.codehaus.org/display/MAVENUSER/POM+Element+for+Source+File+Encoding) guide to use the property. From my understanding, this property is not defined in the Maven model at all, since can be null. I do not think we can force users to define it, so i decided to use a default value (UTF-8). But i am open to any suggestions on this. Also i am wonder: should we make this read-only? In that case, users could not set it in the mojo config, only with the global property (however, in special situations they may want to use a different value for that).

Configurable encoding for listing text files

---

src/main/java/com/jayway/maven/plugins/android/AbstractAndroidMojo.java
src/main/java/com/jayway/maven/plugins/android/phase_prebuild/ClasspathModifierLifecycleParticipant.java
src/main/java/com/jayway/maven/plugins/android/phase_prebuild/ProvidedDependencyChecker.java

Warn about conflicting dependencies

---

src/main/java/com/jayway/maven/plugins/android/phase04processclasses/ProguardMojo.java
src/main/java/com/jayway/maven/plugins/android/phase09package/AarMojo.java

Gradle has a feature, where you can specify consumerProguardFiles to include
a proguard configuration into an aar artifact.
See https://plus.google.com/+IanLake/posts/1HfDuFFkMXG for more info about
consumerProguardFiles.
This pr only covers using the included proguard files. Including a proguard configuration into aars generated by maven is still open. 
refs #611

Implemented using aar consumer proguard configurations in ProguardMojo

---

src/main/java/com/jayway/maven/plugins/android/configuration/ManifestMerger.java
src/main/java/com/jayway/maven/plugins/android/configuration/RegexVersionElementParser.java
src/main/java/com/jayway/maven/plugins/android/configuration/SimpleVersionElementParser.java
src/main/java/com/jayway/maven/plugins/android/configuration/VersionElementParser.java
src/main/java/com/jayway/maven/plugins/android/configuration/VersionGenerator.java
src/main/java/com/jayway/maven/plugins/android/standalonemojos/ManifestMergerMojo.java
src/test/java/com/jayway/maven/plugins/android/configuration/RegexVersionElementParserTest.java
src/test/java/com/jayway/maven/plugins/android/configuration/SimpleVersionElementParserTest.java
src/test/java/com/jayway/maven/plugins/android/configuration/VersionGeneratorTest.java

This fixes #605, complete with test cases. Hopefully I didn't miss anything important (the XML part is automatically done by the mojo, right?); please review.
Thanks!

Regex support for VersionGenerator

---

src/main/java/com/simpligility/maven/plugins/android/configuration/VersionGenerator.java
src/main/java/com/simpligility/maven/plugins/android/standalonemojos/ManifestMergerMojo.java

Hello everyone,
It seems as one major use case was overlooked while working on #605 and #606. What happens if Maven descriptor maintainer DOES NOT include or declare the *versionNamingPattern* property? Or leaves it blank. Judging by the way Maven behaves, the propery would evaluate to *null*, and cause a NullPointerException when accessing the value in *VersionGenetator* class constructor. Setting *Parameter* annotation *defaultValue* to empty parenthesis does not help much.
Hence there are two options. Either something is totally wrong with Maven 3.2.1 I am using (which could be the case after all), or the fix proposed here solves the issue at hand, without breaking anything.

Fixed a NullPointerException if versionNamingPattern is not defined

---

src/main/java/com/simpligility/maven/plugins/android/phase_prebuild/ClasspathModifierLifecycleParticipant.java

Instead of just an empty file which will break things if it is not replaced by a real classes.jar
Fix for #626

Using a proper empty jar as the default classes.jar 

---

.travis.yml
src/main/java/com/simpligility/maven/plugins/android/asm/AndroidTestFinder.java
src/main/java/com/simpligility/maven/plugins/android/asm/AnnotatedFinder.java
src/main/java/com/simpligility/maven/plugins/android/asm/DescendantFinder.java
src/main/java/com/simpligility/maven/plugins/android/phase11preintegrationtest/InternalPreIntegrationTestMojo.java
src/main/java/com/simpligility/maven/plugins/android/phase12integrationtest/InternalIntegrationTestMojo.java
src/test/java/com/simpligility/maven/plugins/android/sample/ApkWithProvidedJarBuildExampleIT.java
src/test/java/com/simpligility/maven/plugins/android/sample/Junit4TestBuildExampleIT.java
src/test/projects/aar-child-junit-tests/aar-child-library/pom.xml
src/test/projects/aar-child-junit-tests/aar-child-library/src/main/AndroidManifest.xml
src/test/projects/aar-child-junit-tests/aar-child-library/src/main/java/org/jboss/aerogear/android/parent/ParentStoryTeller.java
src/test/projects/aar-child-junit-tests/aar-child-library/src/main/res/values/strings.xml
src/test/projects/aar-child-junit-tests/aar-child-test/pom.xml
src/test/projects/aar-child-junit-tests/aar-child-test/src/main/AndroidManifest.xml
src/test/projects/aar-child-junit-tests/aar-child-test/src/main/java/org/jboss/aerogear/android/parent/test/ParentAndGrandparentTest.java
src/test/projects/aar-child-junit-tests/aar-child-test/src/main/res/values/strings.xml
src/test/projects/aar-child-junit-tests/pom.xml
src/test/projects/aar-child/aar-child-test/pom.xml
src/test/projects/tictactoe/pom.xml

Fixes https://github.com/simpligility/android-maven-plugin/issues/623 and supplies JUnit runner.
Also fixes https://github.com/simpligility/android-maven-plugin/issues/617 (see a9f051f)

Junit4 test runner

---

.travis.yml
src/main/java/com/simpligility/maven/plugins/android/AbstractAndroidMojo.java
src/main/java/com/simpligility/maven/plugins/android/AndroidSdk.java
src/main/java/com/simpligility/maven/plugins/android/configuration/Sdk.java
src/site/asciidoc/changelog.adoc
src/test/java/com/simpligility/maven/plugins/android/AndroidSdkTest.java

This PR adds the ability to choose which the version of the build tools we want to use.
<sdk>
<platform>22</platform>
</sdk>
A) When a user does not set the build tools it will behaves exactly as it is now.
B) If the user decide to put a build tool it will try to find that version of the build tools or throw an exception.
I prefer this approach over the one where if it cannot find the build tools specified it will take the latest one... I assume if I user set that value there must be a reason and we don't want to use another build tool version. (With a CI you can be sure your PC and the CI uses the same build tools)
Note about the code:
When we receive an AndroidTarget for version 19 from the google lib it gives us the correct target but the target will always try to find the latest build …

Feature choose which version of the build tools to use

---

src/main/java/com/simpligility/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java
src/main/java/com/simpligility/maven/plugins/android/phase09package/ApkMojo.java

If you want to add additional raw file directories to the apk, you can specify them in extra arguments - however, these should come last in the aapt command (with the exception of `--output-text-symbols` - which is used when generating the `R.txt` file.  This PR just moves the `addExtraArguments` call later in the command list.

Add extra arguments at (or near) the end of aapt command

---

src/main/java/com/simpligility/maven/plugins/android/phase01generatesources/MavenILogger.java
src/main/java/com/simpligility/maven/plugins/android/standalonemojos/ManifestMergerMojo.java
src/site/asciidoc/changelog.adoc

Currently, when you do manifest merging, it writes out all entries as `info` entries.  When you are storing the report to a file (using the `mergeReportFile` configuration parameter), this is extra information that doesn't need to be output to the screen (because it's in the file).  This patch adds an option to MavenILogger to treat `info` calls as `verbose`, and then uses that flag whenever the `mergeReportFile` parameter is specified.

Make manifest merging less verbose

---

src/main/java/com/simpligility/maven/plugins/android/phase09package/ApkMojo.java

The error is occurring in method removeDuplicatesFromJar at line 830 of class ApkMojo in package com.simpligility.maven.plugins.android.phase09package:
duplicateZos.putNextEntry( entry );
The error is genuine in that the ZipEntry "entry" is a duplicate. The previous line failed to correctly detect a duplicate because the logic is reversed:
!duplicatesAdded.add( entry.getName() )
API: HashSet.add() returns true if this set did not already contain the specified element.
This change corrects indicated statement at line 828 by removing the exclamation mark in front of "duplicatessAdded".
1 file changed, 1 insertion(+), 1 deletion(-)

Fix duplicate file detection logic - Issue 660

---

src/main/java/com/simpligility/maven/plugins/android/common/UnpackedLibHelper.java
src/main/java/com/simpligility/maven/plugins/android/phase_prebuild/ClasspathModifierLifecycleParticipant.java

-add dummy ZipEntry to apk placeholder. to avoid "0 entries" exception.  
-Changed system dependency to use BaseVersion for snapshot versions.
I had issue where the ClasspathModifierLifecycleParticipent used the
full snapshot version with timestamp for the placeholder and system dependency.
But the GenerateSourcesMojo used the SNAPSHOT version without timestamp, resulting in compilation errors.  Because actual apk classes.jar wasn't getting added to the classpath.
Note:  I experience these problems specifically when there wasn't any artifacts in the local repo.  I was doing a verify on an aggregator project, which had both the apk and test projects as modules.  So the apk had to come from the previous build, instead of the maven repo.  I think this had something to do with the problem.  I …

Fixes for provided apk dependency for instrumentation tests

---

src/main/java/com/simpligility/maven/plugins/android/AndroidNdk.java
src/site/asciidoc/changelog.adoc

At least on NDK version r10e, the GDB server for armeabi is now located in `<NDK_ROOT>/prebuilt/android-arm/gdbserver`.

Also check directory called "android-arm" for gdb server

---

src/test/projects/libraryprojects/pom.xml

] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project libraryprojects-parent: failed to get report for org.apache.maven.plugins:maven-javadoc-plugin: Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.3.0:generate-sources (default-generate-sources) on project libraryprojects-tests: Execution default-generate-sources of goal com.simpligility.maven.plugins:android-maven-plugin:4.3.0:generate-sources failed: String index out of range: -1 -> [Help 1]

#655 Maven site command fails with test projects

---

src/main/java/com/simpligility/maven/plugins/android/phase04processclasses/ProguardMojo.java

Fix for https://github.com/simpligility/android-maven-plugin/issues/704. 
Adds to the `proguardCommand` the `proguard.txt` files from all dependencies (direct and transitive) instead of direct dependencies only.

#704 Include proguard configuration file of all dependencies

---

src/main/resources/META-INF/plexus/components.xml

When I followed the instructions at : http://simpligility.github.io/android-maven-plugin/emma.html I noticed that my coverage.em file was not being generated in my library module but it was in my test module.  I did some sleuthing and noticed the emma mojo wan't included for the aar packaging type.  I've updated this in the components file and have code coverage for my projects.

Emma coverage was not applied to apklib or aar projects.  Now it is

---

pom.xml
src/main/java/com/simpligility/maven/plugins/android/standalonemojos/ConnectMojo.java
src/main/java/com/simpligility/maven/plugins/android/standalonemojos/DisconnectMojo.java

Connect and disconnect do not work because the logger is null resulting in an NPE.
Furthermore connecting over tcpip needs tcpip enabled.

Fix connect and disconnect to not throw NPE

---

src/main/java/com/simpligility/maven/plugins/android/AbstractInstrumentationMojo.java
src/main/java/com/simpligility/maven/plugins/android/configuration/Test.java

so postIntegrationTest phase executes even if the tests failed.

added testFailSafe option

---

src/main/java/com/simpligility/maven/plugins/android/phase09package/ApkMojo.java
src/test/java/com/simpligility/maven/plugins/android/phase09package/ExtractDuplicatesIT.java
src/test/projects/duplicates/duplicates-app/src/main/resources/META-INF/services/com.jayway.maven.plugins.android.TestInterface
src/test/projects/duplicates/duplicates-app/src/main/resources/resourceC
src/test/projects/duplicates/duplicates-lib-b/src/main/resources/resourceC

extract duplicates functionality only looked at dependent jars, not the project output folder.

also extract duplicates from output folder

---

src/main/java/com/simpligility/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java
src/test/projects/buildConfigInjection/pom.xml

Fix buildConfigConstants parameter

---

pom.xml
src/main/java/com/simpligility/maven/plugins/android/phase04processclasses/ProguardMojo.java

Use Proguard dependency from Central by default

---

src/main/java/com/simpligility/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java

This PR fixes #417 and #573. Note: A similar fix (in GenerateSourcesMojo.generateRForApkLibDependency()) could possibly solve #345 as well, but I haven't had time to verify that (and therefore I will not include a fix for #345 in this PR). 
I tried to use `resourceOverlayDirectory` but ran into problems .... I have specified the following configuration in my pom:
`<resourceOverlayDirectory>src/env/staging/res</resourceOverlayDirectory>`
Without this fix, the project builds fine but when the app starts it (usually) crashes since the resources ids have become messed up.
The problem is the order in which the resource overlay directory and the normal resource directory (src/main/res) ends up being declared in the aapt package command. I observed that the resource overlay directory is declared …

Resource overlays

---

src/main/java/com/simpligility/maven/plugins/android/phase09package/AarMojo.java
src/main/java/com/simpligility/maven/plugins/android/phase09package/ApkMojo.java
src/main/java/com/simpligility/maven/plugins/android/phase09package/ApklibMojo.java

Currently they end up defaulting to the type of the main project artifact.
E.g. in my particular scenario the main artifact is of type `jar` and I am attaching an `aar` with an android-specific variant of the library. Without this patch the attached artifact has type 'jar' instead of 'aar'.

Use correct type for attached artifacts

---

src/main/java/com/simpligility/maven/plugins/android/AndroidSdk.java
src/site/asciidoc/changelog.adoc

In a while this will be able to be changed to API 24, but for now it could definitely stand to be updated to API 23. I'm also not sure if there is any good place (or if it would be desirable) to log in the build process that the android-maven-plugin has decided to choose a default api level, and maybe a reference to the pom option to configure it.

Update Default SDK Version to API 23

---

pom.xml
src/main/java/com/simpligility/maven/plugins/android/phase09package/AarMojo.java

The documentation for the aar goal claims to support the attachJar parameter. This patch uses the code from the legacy ApklibMojo to add support for building a jar file.

Add support to install jar file in aar artifact

---

pom.xml
src/conf/maven_checks.xml
src/main/java/com/simpligility/maven/plugins/android/AndroidSdk.java
src/main/java/com/simpligility/maven/plugins/android/phase01generatesources/ClassLoaderFactory.java
src/main/java/com/simpligility/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java
src/main/java/com/simpligility/maven/plugins/android/phase01generatesources/ResourceClassGenerator.java

Don't generate R.java if one has already been generated for that package in the compile classpath.
This stops extra R javas being generated for a test-apk that will mirror those from the target APK.

Don't generate existing R

---

pom.xml
src/main/java/com/simpligility/maven/plugins/android/AndroidSdk.java
src/main/java/com/simpligility/maven/plugins/android/configuration/D8.java
src/main/java/com/simpligility/maven/plugins/android/configuration/Dex.java
src/main/java/com/simpligility/maven/plugins/android/phase08preparepackage/D8Mojo.java
src/main/java/com/simpligility/maven/plugins/android/phase08preparepackage/DexMechanism.java
src/main/java/com/simpligility/maven/plugins/android/phase08preparepackage/DexMojo.java
src/main/resources/META-INF/plexus/components.xml

D8 is the new dex mechanism available in the Android 28 tools.
It allows for use of and desugaring of Java8 syntax.
To use add a
```
<DexMachansim>D8</DexMechansim>
```
element to your config.

Allowing D8 instead of Dex

---

pom.xml
src/main/java/com/simpligility/maven/plugins/android/AbstractEmulatorMojo.java
src/main/java/com/simpligility/maven/plugins/android/configuration/Emulator.java

Configurable path to Emulator folder

Path to emulator

---

src/main/java/com/simpligility/maven/plugins/android/AndroidSdk.java

Changes in Android SDK Tools, Revision 25.3.0 which affect android-maven-plugin [Read more](https://developer.android.com/studio/releases/sdk-tools)
Executables have been moved to tools/bin/ from tools:
- lint
- monkeyrunner
Previous implementation gets these tools from sdk/tools
Current fix change this behaviour and now plugin gets tools from sdk/tools/bin/

Fixed path to lint, monkeyrunner, apkbuilder following changes in Android SDK Tools, Revision 25.3.0

---

pom.xml
src/main/java/com/simpligility/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java
src/main/java/com/simpligility/maven/plugins/android/phase08preparepackage/D8Mojo.java
src/test/java/com/simpligility/maven/plugins/android/AndroidSdkTest.java
src/test/java/com/simpligility/maven/plugins/android/SdkTestSupport.java

Also updated build tools versions in tests to 30.0.2 (which is latest as of 15-NOV-2020)

Allowing D8 to be invoked inj build tools 29+.

---

src/main/java/com/simpligility/maven/plugins/android/phase08preparepackage/D8Mojo.java

The mainDexList option was not working - no space between the command and the filename

Fix mainDexList so that the filename is separated from the command
